//! Synonym map — pipeline-stage canonicalization (variant → canonical).
//!
//! Graduated from `experimental/kg-validation/src/synonyms.rs` per
//! Wave 2 Task 4 (`mb-nccf`) — load-bearing per ADR 0049 Amendment A2
//! (v1.1 starting point + v1 open-vocab canonicalization). The only
//! changes from the sandbox are the `anyhow` → `thiserror` swap
//! (binding parameter D3) and import paths (`crate::passes::normalize`
//! → `crate::kg::passes::normalize`, expressed as `super::`).
//!
//! ## Architectural insight (preserved from the sandbox docstring)
//!
//! **Synonym canonicalization is a pipeline-stage concern, not a
//! scoring concern.** Wave 0.5.3 iter 1 and iter 2 failed because the
//! closed-vocab validator dropped `automobile-repair` BEFORE the
//! scorer's `SynonymMap` could collapse it to `car-repair`. With the
//! map applied in-band at validate-time, an in-vocab canonical form
//! is recognised regardless of which variant the model emitted.
//!
//! The synonym-map JSON on disk is generated by
//! `experimental/kg-validation/scripts/generate-synonym-map.ps1` (still
//! in the sandbox per binding parameter D5). See ADR 0048 §G7 for
//! authoring discipline.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use thiserror::Error;

use super::passes::normalize::normalize_tags;

/// Errors the synonym loader can produce. Variants are flat for the
/// same reasons as `OllamaError` — every consumer either logs and
/// continues or aborts; nobody recovers structurally.
#[derive(Debug, Error)]
pub enum SynonymError {
    #[error("synonym-map read failed at {path}: {error}")]
    Io { path: PathBuf, error: String },
    #[error("synonym-map parse failed at {path}: {error}")]
    Parse { path: PathBuf, error: String },
    #[error("synonym-map schema_version mismatch at {path}: got {got:?}, want synonym-map-v1")]
    VersionMismatch { path: PathBuf, got: String },
    #[error(
        "synonym-map collision at {path}: variant {variant:?} maps to both {first:?} and {second:?}"
    )]
    Collision {
        path: PathBuf,
        variant: String,
        first: String,
        second: String,
    },
}

/// On-disk synonym map schema. Mirrors the JSON file produced by
/// the sandbox-side authoring script.
#[derive(Debug, Clone, Deserialize)]
pub struct SynonymMapFile {
    pub version: String,
    pub schema_version: String,
    #[serde(default)]
    pub generated_from: Vec<String>,
    #[serde(default)]
    pub discipline_notes: String,
    pub synonyms: Vec<SynonymEntry>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SynonymEntry {
    pub canonical: String,
    pub variants: Vec<String>,
    #[serde(default)]
    pub rationale: String,
    pub source: String,
}

/// Loaded synonym map. The variant index is a flat lookup table:
/// every variant -> its canonical. Canonicals self-map (so a tag
/// already in canonical form survives unchanged). Unknown tags pass
/// through identity at canonicalization time.
#[derive(Debug, Clone)]
pub struct SynonymMap {
    pub version: String,
    pub schema_version: String,
    /// variant (or canonical) -> canonical
    pub variant_to_canonical: BTreeMap<String, String>,
}

impl SynonymMap {
    pub fn load(path: &Path) -> Result<Self, SynonymError> {
        let text = std::fs::read_to_string(path).map_err(|e| SynonymError::Io {
            path: path.to_path_buf(),
            error: e.to_string(),
        })?;
        let file: SynonymMapFile =
            serde_json::from_str(&text).map_err(|e| SynonymError::Parse {
                path: path.to_path_buf(),
                error: e.to_string(),
            })?;
        Self::from_file_with_source(file, path)
    }

    /// Build a map from an already-parsed file struct. Useful for
    /// tests that construct the JSON inline. The `source_path` is
    /// only used to enrich error messages.
    pub fn from_file_with_source(
        file: SynonymMapFile,
        source_path: &Path,
    ) -> Result<Self, SynonymError> {
        if file.schema_version != "synonym-map-v1" {
            return Err(SynonymError::VersionMismatch {
                path: source_path.to_path_buf(),
                got: file.schema_version,
            });
        }
        let mut idx: BTreeMap<String, String> = BTreeMap::new();
        for e in &file.synonyms {
            // Canonical self-maps.
            idx.insert(e.canonical.clone(), e.canonical.clone());
            for v in &e.variants {
                if let Some(existing) = idx.get(v) {
                    if existing != &e.canonical {
                        return Err(SynonymError::Collision {
                            path: source_path.to_path_buf(),
                            variant: v.clone(),
                            first: existing.clone(),
                            second: e.canonical.clone(),
                        });
                    }
                }
                idx.insert(v.clone(), e.canonical.clone());
            }
        }
        Ok(Self {
            version: file.version,
            schema_version: file.schema_version,
            variant_to_canonical: idx,
        })
    }

    /// Canonicalize a single tag. Re-normalizes via the pipeline
    /// rules first (defensive against authoring slips), then maps
    /// via the synonym index. Unknown tags pass through their
    /// normalized form unchanged.
    pub fn canonicalize(&self, tag: &str) -> String {
        let normalized = normalize_tags(&[tag.to_string()])
            .into_iter()
            .next()
            .unwrap_or_default();
        if normalized.is_empty() {
            return normalized;
        }
        self.variant_to_canonical
            .get(&normalized)
            .cloned()
            .unwrap_or(normalized)
    }

    /// Canonicalize a whole set of tags. Set semantics — duplicates
    /// after canonicalization collapse, order is irrelevant.
    pub fn canonicalize_set(&self, tags: &[String]) -> BTreeSet<String> {
        tags.iter()
            .map(|t| self.canonicalize(t))
            .filter(|t| !t.is_empty())
            .collect()
    }

    /// Canonicalize a slice of tags preserving first-seen order and
    /// dropping duplicates after canonicalization. Used by callers
    /// like the closed-vocab tag validator that care about Vec
    /// ordering for downstream artifact stability.
    pub fn canonicalize_ordered(&self, tags: &[String]) -> Vec<String> {
        let mut out: Vec<String> = Vec::with_capacity(tags.len());
        for t in tags {
            let c = self.canonicalize(t);
            if c.is_empty() {
                continue;
            }
            if !out.iter().any(|existing| existing == &c) {
                out.push(c);
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn map_from_json(s: &str) -> SynonymMap {
        let p = std::env::temp_dir().join(format!(
            "kg-synonyms-test-{}-{}.json",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        std::fs::write(&p, s).unwrap();
        let m = SynonymMap::load(&p).unwrap();
        let _ = std::fs::remove_file(&p);
        m
    }

    fn tiny_map() -> SynonymMap {
        map_from_json(
            r#"{
              "version": "test-v0",
              "schema_version": "synonym-map-v1",
              "synonyms": [
                {"canonical": "car-repair", "variants": ["auto-maintenance", "vehicle-repair", "automobile-repair"], "rationale": "", "source": "test"},
                {"canonical": "meeting",    "variants": ["standup", "1on1"], "rationale": "", "source": "test"},
                {"canonical": "kid",        "variants": [], "rationale": "", "source": "test"}
              ]
            }"#,
        )
    }

    fn s(v: &[&str]) -> Vec<String> {
        v.iter().map(|x| x.to_string()).collect()
    }

    #[test]
    fn schema_version_mismatch_rejected() {
        let p = std::env::temp_dir().join("syn-bad-schema.json");
        std::fs::write(
            &p,
            r#"{"version":"v1","schema_version":"synonym-map-v0","synonyms":[]}"#,
        )
        .unwrap();
        let err = SynonymMap::load(&p).expect_err("should reject");
        assert!(matches!(err, SynonymError::VersionMismatch { .. }), "{err}");
    }

    #[test]
    fn collision_detected() {
        let p = std::env::temp_dir().join("syn-collision.json");
        std::fs::write(
            &p,
            r#"{
              "version":"v1",
              "schema_version":"synonym-map-v1",
              "synonyms":[
                {"canonical":"a","variants":["x"],"rationale":"","source":"t"},
                {"canonical":"b","variants":["x"],"rationale":"","source":"t"}
              ]
            }"#,
        )
        .unwrap();
        let err = SynonymMap::load(&p).expect_err("should reject");
        assert!(matches!(err, SynonymError::Collision { .. }), "{err}");
    }

    #[test]
    fn canonicalize_normalizes_first() {
        let m = tiny_map();
        assert_eq!(m.canonicalize("Standups"), "meeting");
        assert_eq!(m.canonicalize("vehicle_repair"), "car-repair");
        assert_eq!(m.canonicalize("Automobile-Repair"), "car-repair");
        assert_eq!(m.canonicalize("KIDS"), "kid");
    }

    #[test]
    fn unknown_tag_passes_through_normalized() {
        let m = tiny_map();
        assert_eq!(m.canonicalize("brake-pads"), "brake-pad");
        assert_eq!(m.canonicalize("unrecognized"), "unrecognized");
    }

    #[test]
    fn canonicalize_set_collapses_duplicates_after_mapping() {
        let m = tiny_map();
        let out = m.canonicalize_set(&s(&["standup", "1on1", "kids"]));
        let mut expected = BTreeSet::new();
        expected.insert("meeting".to_string());
        expected.insert("kid".to_string());
        assert_eq!(out, expected);
    }

    #[test]
    fn canonicalize_ordered_preserves_first_seen_order_and_dedupes() {
        let m = tiny_map();
        // standup and 1on1 both → meeting; first wins; brake-pads is
        // unknown but normalizes; kids → kid.
        let out = m.canonicalize_ordered(&s(&["standup", "brake-pads", "1on1", "kids"]));
        assert_eq!(out, vec!["meeting", "brake-pad", "kid"]);
    }

    #[test]
    fn canonicalize_ordered_drops_empties() {
        let m = tiny_map();
        let out = m.canonicalize_ordered(&s(&["   ", "kids"]));
        assert_eq!(out, vec!["kid"]);
    }
}
