//! Synonym map — pipeline-stage canonicalization (variant → canonical).
//!
//! This module used to live inside `crate::scoring::tag_collapse`. It
//! was lifted out in Wave 0.5.3 iter 3 (`mb-e10v`) so the closed-vocab
//! tag validator (`crate::passes::tag_validator`) can consume the same
//! canonicalization the scorer uses — without the validator depending
//! on the scoring module's heavier API surface.
//!
//! The architectural insight that motivated the lift:
//! **synonym canonicalization is a pipeline-stage concern, not a
//! scoring concern.** Wave 0.5.3 iter 1 and iter 2 failed because the
//! closed-vocab validator dropped `automobile-repair` BEFORE the
//! scorer's `SynonymMap` could collapse it to `car-repair`. With the
//! map applied in-band at validate-time, an in-vocab canonical form
//! is recognised regardless of which variant the model emitted.
//!
//! The synonym-map JSON on disk is generated by
//! `scripts/generate-synonym-map.ps1` from the answer-key vocabulary
//! plus Bernard's hand-augmented seeds and diff-driven discovery.
//! See ADR 0048 §G7 for the authoring procedure and discipline rules.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::passes::normalize::normalize_tags;

/// On-disk synonym map schema. Mirrors the JSON file produced by
/// `experimental/kg-validation/scripts/generate-synonym-map.ps1`.
#[derive(Debug, Clone, Deserialize)]
pub struct SynonymMapFile {
    pub version: String,
    pub schema_version: String,
    #[serde(default)]
    pub generated_from: Vec<String>,
    #[serde(default)]
    pub discipline_notes: String,
    pub synonyms: Vec<SynonymEntry>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SynonymEntry {
    pub canonical: String,
    pub variants: Vec<String>,
    #[serde(default)]
    pub rationale: String,
    pub source: String,
}

/// Loaded synonym map. The variant index is a flat lookup table:
/// every variant -> its canonical. Canonicals self-map (so a tag
/// already in canonical form survives unchanged). Unknown tags pass
/// through identity at canonicalization time.
#[derive(Debug, Clone)]
pub struct SynonymMap {
    pub version: String,
    pub schema_version: String,
    /// variant (or canonical) -> canonical
    pub variant_to_canonical: BTreeMap<String, String>,
}

impl SynonymMap {
    pub fn load(path: &Path) -> anyhow::Result<Self> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("read {}: {e}", path.display()))?;
        let file: SynonymMapFile = serde_json::from_str(&text)
            .map_err(|e| anyhow::anyhow!("parse {}: {e}", path.display()))?;
        Self::from_file(file)
    }

    /// Build a map from an already-parsed file struct. Useful for
    /// tests that construct the JSON inline.
    pub fn from_file(file: SynonymMapFile) -> anyhow::Result<Self> {
        if file.schema_version != "synonym-map-v1" {
            anyhow::bail!(
                "synonym-map schema_version mismatch: got {:?}, want synonym-map-v1",
                file.schema_version
            );
        }
        let mut idx: BTreeMap<String, String> = BTreeMap::new();
        for e in &file.synonyms {
            // Canonical self-maps.
            idx.insert(e.canonical.clone(), e.canonical.clone());
            for v in &e.variants {
                // Detect collisions: a variant mapped to two different
                // canonicals is an authoring bug — caller should fix
                // the JSON, not silently lose data.
                if let Some(existing) = idx.get(v) {
                    if existing != &e.canonical {
                        anyhow::bail!(
                            "synonym-map collision: variant {:?} maps to both {:?} and {:?}",
                            v,
                            existing,
                            e.canonical
                        );
                    }
                }
                idx.insert(v.clone(), e.canonical.clone());
            }
        }
        Ok(Self {
            version: file.version,
            schema_version: file.schema_version,
            variant_to_canonical: idx,
        })
    }

    /// Canonicalize a single tag. Re-normalizes via the pipeline
    /// rules first (defensive against authoring slips), then maps
    /// via the synonym index. Unknown tags pass through their
    /// normalized form unchanged.
    pub fn canonicalize(&self, tag: &str) -> String {
        let normalized = normalize_tags(&[tag.to_string()])
            .into_iter()
            .next()
            .unwrap_or_default();
        if normalized.is_empty() {
            return normalized;
        }
        self.variant_to_canonical
            .get(&normalized)
            .cloned()
            .unwrap_or(normalized)
    }

    /// Canonicalize a whole set of tags. Set semantics — duplicates
    /// after canonicalization collapse, order is irrelevant.
    pub fn canonicalize_set(&self, tags: &[String]) -> BTreeSet<String> {
        tags.iter()
            .map(|t| self.canonicalize(t))
            .filter(|t| !t.is_empty())
            .collect()
    }

    /// Canonicalize a slice of tags preserving first-seen order and
    /// dropping duplicates after canonicalization. Used by callers
    /// like the closed-vocab tag validator that care about Vec
    /// ordering for downstream artifact stability.
    pub fn canonicalize_ordered(&self, tags: &[String]) -> Vec<String> {
        let mut out: Vec<String> = Vec::with_capacity(tags.len());
        for t in tags {
            let c = self.canonicalize(t);
            if c.is_empty() {
                continue;
            }
            if !out.iter().any(|existing| existing == &c) {
                out.push(c);
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn map_from_json(s: &str) -> SynonymMap {
        let p = std::env::temp_dir().join(format!(
            "kg-synonyms-test-{}-{}.json",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        std::fs::write(&p, s).unwrap();
        let m = SynonymMap::load(&p).unwrap();
        let _ = std::fs::remove_file(&p);
        m
    }

    fn tiny_map() -> SynonymMap {
        map_from_json(
            r#"{
              "version": "test-v0",
              "schema_version": "synonym-map-v1",
              "synonyms": [
                {"canonical": "car-repair", "variants": ["auto-maintenance", "vehicle-repair", "automobile-repair"], "rationale": "", "source": "test"},
                {"canonical": "meeting",    "variants": ["standup", "1on1"], "rationale": "", "source": "test"},
                {"canonical": "kid",        "variants": [], "rationale": "", "source": "test"}
              ]
            }"#,
        )
    }

    fn s(v: &[&str]) -> Vec<String> {
        v.iter().map(|x| x.to_string()).collect()
    }

    #[test]
    fn schema_version_mismatch_rejected() {
        let p = std::env::temp_dir().join("syn-bad-schema.json");
        std::fs::write(
            &p,
            r#"{"version":"v1","schema_version":"synonym-map-v0","synonyms":[]}"#,
        )
        .unwrap();
        let err = SynonymMap::load(&p).expect_err("should reject");
        assert!(format!("{err}").contains("schema_version mismatch"));
    }

    #[test]
    fn collision_detected() {
        let p = std::env::temp_dir().join("syn-collision.json");
        std::fs::write(
            &p,
            r#"{
              "version":"v1",
              "schema_version":"synonym-map-v1",
              "synonyms":[
                {"canonical":"a","variants":["x"],"rationale":"","source":"t"},
                {"canonical":"b","variants":["x"],"rationale":"","source":"t"}
              ]
            }"#,
        )
        .unwrap();
        let err = SynonymMap::load(&p).expect_err("should reject");
        assert!(format!("{err}").contains("collision"));
    }

    #[test]
    fn canonicalize_normalizes_first() {
        let m = tiny_map();
        assert_eq!(m.canonicalize("Standups"), "meeting");
        assert_eq!(m.canonicalize("vehicle_repair"), "car-repair");
        assert_eq!(m.canonicalize("Automobile-Repair"), "car-repair");
        assert_eq!(m.canonicalize("KIDS"), "kid");
    }

    #[test]
    fn unknown_tag_passes_through_normalized() {
        let m = tiny_map();
        assert_eq!(m.canonicalize("brake-pads"), "brake-pad");
        assert_eq!(m.canonicalize("unrecognized"), "unrecognized");
    }

    #[test]
    fn canonicalize_set_collapses_duplicates_after_mapping() {
        let m = tiny_map();
        let out = m.canonicalize_set(&s(&["standup", "1on1", "kids"]));
        let mut expected = BTreeSet::new();
        expected.insert("meeting".to_string());
        expected.insert("kid".to_string());
        assert_eq!(out, expected);
    }

    #[test]
    fn canonicalize_ordered_preserves_first_seen_order_and_dedupes() {
        let m = tiny_map();
        // standup and 1on1 both → meeting; first wins; brake-pads is
        // unknown but normalizes; kids → kid.
        let out = m.canonicalize_ordered(&s(&["standup", "brake-pads", "1on1", "kids"]));
        assert_eq!(out, vec!["meeting", "brake-pad", "kid"]);
    }

    #[test]
    fn canonicalize_ordered_drops_empties() {
        let m = tiny_map();
        let out = m.canonicalize_ordered(&s(&["   ", "kids"]));
        assert_eq!(out, vec!["kid"]);
    }
}
