//! Deterministic tag-collapse scoring per ADR 0048 Â§G7.
//!
//! Supersedes the LLM tag-equivalence judge for the tag-collapse
//! metric only. The judge architecture in [`crate::scoring::judge`] +
//! [`crate::scoring::judge_validation`] is preserved for any future
//! LLM-judged metric; it is not invoked here.
//!
//! ## Algorithm (per pipeline entry)
//!
//! 1. Canonicalize the entry's `topic_tags` via the synonym map.
//!    Canonicalization is (a) re-normalize via the pipeline rules
//!    in [`crate::passes::normalize`] (defends against authoring
//!    slips in the answer keys) then (b) look the result up in the
//!    synonym map's variant-to-canonical index, falling back to the
//!    input if no mapping exists.
//! 2. Canonicalize every `acceptable_topic_tag_sets[i]` from the
//!    answer key the same way.
//! 3. Compute the Jaccard similarity between the actual canonical
//!    set and each acceptable canonical set. Take the MAX.
//! 4. **Pass condition:** `MAX(jaccard) == 1.0` â€” i.e. exact set
//!    equality on at least one acceptable set after canonicalization.
//! 5. Record Jaccard at lower thresholds (0.8, 0.67, 0.5) as
//!    observational sidecars; they do not gate.
//! 6. For non-passing entries, record every `(actual_tag, expected_tag)`
//!    pair that contributed to the symmetric difference vs. the
//!    best-matching acceptable set. These feed the near-miss aggregator.
//!
//! ## Why exact match (Jaccard 1.0)?
//!
//! The synonym map IS the equivalence engine. Accepting partial
//! overlap on top of it double-counts forgiveness and obscures map
//! gaps. Misses at 1.0 point directly to synonym-map candidates for
//! the Wave 5 iteration loop â€” which is the metric's intended
//! feedback loop. ADR 0048 Â§G7 rationale.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::passes::normalize::normalize_tags;
use crate::schema::AnswerKey;

// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Synonym map
// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

/// On-disk synonym map schema. Generated by
/// `experimental/kg-validation/scripts/generate-synonym-map.ps1` from
/// the answer-key vocabulary + Bernard's hand-augmented seeds +
/// diff-driven discovery. See ADR 0048 Â§G7 for the authoring
/// procedure + discipline rules.
#[derive(Debug, Clone, Deserialize)]
pub struct SynonymMapFile {
    pub version: String,
    pub schema_version: String,
    #[serde(default)]
    pub generated_from: Vec<String>,
    #[serde(default)]
    pub discipline_notes: String,
    pub synonyms: Vec<SynonymEntry>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SynonymEntry {
    pub canonical: String,
    pub variants: Vec<String>,
    #[serde(default)]
    pub rationale: String,
    pub source: String,
}

/// Loaded synonym map. The variant index is a flat lookup table:
/// every variant -> its canonical. Canonicals self-map (so a tag
/// already in canonical form survives unchanged). Unknown tags pass
/// through identity at canonicalization time.
#[derive(Debug, Clone)]
pub struct SynonymMap {
    pub version: String,
    pub schema_version: String,
    /// variant (or canonical) -> canonical
    pub variant_to_canonical: BTreeMap<String, String>,
}

impl SynonymMap {
    pub fn load(path: &Path) -> anyhow::Result<Self> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("read {}: {e}", path.display()))?;
        let file: SynonymMapFile = serde_json::from_str(&text)
            .map_err(|e| anyhow::anyhow!("parse {}: {e}", path.display()))?;
        if file.schema_version != "synonym-map-v1" {
            anyhow::bail!(
                "synonym-map schema_version mismatch: got {:?}, want synonym-map-v1",
                file.schema_version
            );
        }
        let mut idx: BTreeMap<String, String> = BTreeMap::new();
        for e in &file.synonyms {
            // Canonical self-maps.
            idx.insert(e.canonical.clone(), e.canonical.clone());
            for v in &e.variants {
                // Detect collisions: a variant mapped to two different
                // canonicals is an authoring bug â€” caller should fix
                // the JSON, not silently lose data.
                if let Some(existing) = idx.get(v) {
                    if existing != &e.canonical {
                        anyhow::bail!(
                            "synonym-map collision: variant {:?} maps to both {:?} and {:?}",
                            v,
                            existing,
                            e.canonical
                        );
                    }
                }
                idx.insert(v.clone(), e.canonical.clone());
            }
        }
        Ok(Self {
            version: file.version,
            schema_version: file.schema_version,
            variant_to_canonical: idx,
        })
    }

    /// Canonicalize a single tag. Re-normalizes via the pipeline
    /// rules first (defensive against authoring slips), then maps
    /// via the synonym index. Unknown tags pass through their
    /// normalized form unchanged.
    pub fn canonicalize(&self, tag: &str) -> String {
        let normalized = normalize_tags(&[tag.to_string()])
            .into_iter()
            .next()
            .unwrap_or_default();
        if normalized.is_empty() {
            return normalized;
        }
        self.variant_to_canonical
            .get(&normalized)
            .cloned()
            .unwrap_or(normalized)
    }

    /// Canonicalize a whole set of tags. Set semantics â€” duplicates
    /// after canonicalization collapse, order is irrelevant.
    pub fn canonicalize_set(&self, tags: &[String]) -> BTreeSet<String> {
        tags.iter()
            .map(|t| self.canonicalize(t))
            .filter(|t| !t.is_empty())
            .collect()
    }
}

// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Per-entry + per-run scoring
// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

/// Jaccard similarity of two sets. Empty-vs-empty is defined as 1.0
/// (both "no tags expected, no tags emitted" is full agreement); this
/// matters when an answer-key entry intentionally has an empty
/// acceptable set (rare but legal).
fn jaccard(a: &BTreeSet<String>, b: &BTreeSet<String>) -> f64 {
    if a.is_empty() && b.is_empty() {
        return 1.0;
    }
    let intersect = a.intersection(b).count();
    let union = a.union(b).count();
    if union == 0 {
        return 0.0;
    }
    intersect as f64 / union as f64
}

#[derive(Debug, Clone, Serialize)]
pub struct TagCollapseEntry {
    pub dictation_id: String,
    pub entry_idx: usize,
    pub actual_raw: Vec<String>,
    pub actual_canonical: BTreeSet<String>,
    /// The acceptable set (already canonical) that produced the
    /// highest Jaccard. Empty when there were no acceptable sets.
    pub best_match_acceptable_canonical: BTreeSet<String>,
    pub best_jaccard: f64,
    pub passed_at_exact: bool,
}

#[derive(Debug, Clone, Serialize)]
pub struct NearMiss {
    /// A tag in `actual_canonical` not in `best_match_acceptable_canonical`,
    /// OR a tag in the best match not in actual. The two directions
    /// are reported jointly because both are synonym-map iteration
    /// candidates.
    pub actual_tag: String,
    pub expected_tag: String,
    pub frequency: usize,
    pub example_dictation_ids: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct TagCollapseScore {
    pub synonym_map_version: String,
    pub total_entries: usize,
    /// Numerator of the primary Â§8.4 metric (Jaccard 1.0).
    pub correct_at_exact: usize,
    /// Observational sidecars â€” count entries with `best_jaccard >= threshold`.
    pub correct_at_0_8: usize,
    pub correct_at_0_67: usize,
    pub correct_at_0_5: usize,
    pub per_entry: Vec<TagCollapseEntry>,
    /// Top-N near-miss pairs ranked by frequency; N = 10 by default.
    pub near_miss_top: Vec<NearMiss>,
}

impl TagCollapseScore {
    /// The Â§8.4 â‰¥ 80% gate operates on this ratio.
    pub fn exact_percentage(&self) -> f64 {
        if self.total_entries == 0 {
            0.0
        } else {
            100.0 * self.correct_at_exact as f64 / self.total_entries as f64
        }
    }
}

/// Input to [`score_tag_collapse`]: one element per gradable
/// (pipeline-entry, answer-key-entry) pair. Junk-bucket entries are
/// excluded by the caller â€” they don't have acceptable tag sets.
/// Owns its data so the test ergonomics stay tolerable (the runtime
/// caller is `build_inputs_from_pairs` which clones once per entry,
/// and the total entry count is ~80, so this is irrelevant for
/// performance).
#[derive(Debug, Clone)]
pub struct TagCollapseInput {
    pub dictation_id: String,
    pub entry_idx: usize,
    pub actual_tags: Vec<String>,
    pub acceptable_tag_sets: Vec<Vec<String>>,
}

pub fn score_tag_collapse(map: &SynonymMap, inputs: &[TagCollapseInput]) -> TagCollapseScore {
    let mut per_entry: Vec<TagCollapseEntry> = Vec::with_capacity(inputs.len());
    let mut correct_at_exact = 0usize;
    let mut correct_at_0_8 = 0usize;
    let mut correct_at_0_67 = 0usize;
    let mut correct_at_0_5 = 0usize;

    // Near-miss aggregation: (actual_tag, expected_tag) -> (count, [example_ids])
    let mut nm_counter: BTreeMap<(String, String), (usize, Vec<String>)> = BTreeMap::new();

    for input in inputs {
        let actual_canonical = map.canonicalize_set(&input.actual_tags);

        let (best_jaccard, best_match) = if input.acceptable_tag_sets.is_empty() {
            // No acceptable set to score against â€” neutral. We
            // exclude such entries from the denominator at the
            // caller, but defensive zero-fill here.
            (0.0, BTreeSet::<String>::new())
        } else {
            // Track the best (j, canon) pair seen so far. Initialize
            // with the first acceptable set even if Jaccard is 0 so
            // near-miss attribution always has SOMETHING to diff
            // against.
            let mut best: Option<(f64, BTreeSet<String>)> = None;
            for set in &input.acceptable_tag_sets {
                let canon = map.canonicalize_set(set);
                let j = jaccard(&actual_canonical, &canon);
                let take = match &best {
                    None => true,
                    Some((cur, _)) => j > *cur,
                };
                if take {
                    best = Some((j, canon));
                }
            }
            best.unwrap_or((0.0, BTreeSet::new()))
        };

        let passed = (best_jaccard - 1.0).abs() < f64::EPSILON;
        if passed {
            correct_at_exact += 1;
        }
        if best_jaccard + 1e-9 >= 0.8 {
            correct_at_0_8 += 1;
        }
        if best_jaccard + 1e-9 >= 0.67 {
            correct_at_0_67 += 1;
        }
        if best_jaccard + 1e-9 >= 0.5 {
            correct_at_0_5 += 1;
        }

        // Accumulate near-misses (only when not passing â€” passed
        // entries have empty symmetric difference by definition).
        if !passed {
            let only_in_actual: Vec<&String> = actual_canonical.difference(&best_match).collect();
            let only_in_expected: Vec<&String> = best_match.difference(&actual_canonical).collect();
            // Cross-product of the symmetric difference: each
            // unmatched-actual-tag paired with each unmatched-
            // expected-tag is a candidate "should have been collapsed
            // to the same canonical". The single-tag-on-one-side case
            // pairs against an empty sentinel "(missing)".
            if only_in_actual.is_empty() && !only_in_expected.is_empty() {
                for e in &only_in_expected {
                    bump_near_miss(
                        &mut nm_counter,
                        "(missing)".to_string(),
                        (*e).clone(),
                        &input.dictation_id,
                    );
                }
            } else if !only_in_actual.is_empty() && only_in_expected.is_empty() {
                for a in &only_in_actual {
                    bump_near_miss(
                        &mut nm_counter,
                        (*a).clone(),
                        "(extra)".to_string(),
                        &input.dictation_id,
                    );
                }
            } else {
                for a in &only_in_actual {
                    for e in &only_in_expected {
                        bump_near_miss(
                            &mut nm_counter,
                            (*a).clone(),
                            (*e).clone(),
                            &input.dictation_id,
                        );
                    }
                }
            }
        }

        per_entry.push(TagCollapseEntry {
            dictation_id: input.dictation_id.clone(),
            entry_idx: input.entry_idx,
            actual_raw: input.actual_tags.clone(),
            actual_canonical,
            best_match_acceptable_canonical: best_match,
            best_jaccard,
            passed_at_exact: passed,
        });
    }

    // Rank near-misses by frequency desc, then alphabetical for
    // stability. Cap at top-10.
    let mut near_miss_top: Vec<NearMiss> = nm_counter
        .into_iter()
        .map(|((a, e), (freq, ids))| NearMiss {
            actual_tag: a,
            expected_tag: e,
            frequency: freq,
            example_dictation_ids: ids,
        })
        .collect();
    near_miss_top.sort_by(|x, y| {
        y.frequency
            .cmp(&x.frequency)
            .then_with(|| x.actual_tag.cmp(&y.actual_tag))
            .then_with(|| x.expected_tag.cmp(&y.expected_tag))
    });
    near_miss_top.truncate(10);

    TagCollapseScore {
        synonym_map_version: map.version.clone(),
        total_entries: per_entry.len(),
        correct_at_exact,
        correct_at_0_8,
        correct_at_0_67,
        correct_at_0_5,
        per_entry,
        near_miss_top,
    }
}

fn bump_near_miss(
    counter: &mut BTreeMap<(String, String), (usize, Vec<String>)>,
    actual: String,
    expected: String,
    dictation_id: &str,
) {
    let entry = counter.entry((actual, expected)).or_insert((0, Vec::new()));
    entry.0 += 1;
    // Keep at most 3 example IDs to avoid runaway lists.
    if entry.1.len() < 3 && !entry.1.iter().any(|x| x == dictation_id) {
        entry.1.push(dictation_id.to_string());
    }
}

/// Convenience helper: build the inputs vector from a slice of
/// (answer-key, actual-entries) pairs. Junk dictations are skipped.
pub fn build_inputs_from_pairs(
    pairs: &[(String, AnswerKey, Vec<crate::schema::Entry>)],
) -> Vec<TagCollapseInput> {
    let mut out = Vec::new();
    for (id, key, actual) in pairs {
        if key.is_junk_no_entry_expected {
            continue;
        }
        for (idx, (expected, actual_entry)) in key.entries.iter().zip(actual.iter()).enumerate() {
            out.push(TagCollapseInput {
                dictation_id: id.clone(),
                entry_idx: idx,
                actual_tags: actual_entry.topic_tags.clone(),
                acceptable_tag_sets: expected.acceptable_topic_tag_sets.clone(),
            });
        }
    }
    out
}

// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Tests
// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

#[cfg(test)]
mod tests {
    use super::*;

    fn map_from_json(s: &str) -> SynonymMap {
        let p = std::env::temp_dir().join(format!(
            "kg-tagcollapse-test-{}-{}.json",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        std::fs::write(&p, s).unwrap();
        let m = SynonymMap::load(&p).unwrap();
        let _ = std::fs::remove_file(&p);
        m
    }

    fn tiny_map() -> SynonymMap {
        map_from_json(
            r#"{
              "version": "test-v0",
              "schema_version": "synonym-map-v1",
              "synonyms": [
                {"canonical": "car-repair",  "variants": ["auto-maintenance", "vehicle-repair"], "rationale": "", "source": "test"},
                {"canonical": "meeting",     "variants": ["standup", "1on1"], "rationale": "", "source": "test"},
                {"canonical": "kid",         "variants": [], "rationale": "", "source": "test"},
                {"canonical": "karen",       "variants": [], "rationale": "", "source": "test"},
                {"canonical": "finance",     "variants": [], "rationale": "", "source": "test"}
              ]
            }"#,
        )
    }

    fn s(v: &[&str]) -> Vec<String> {
        v.iter().map(|x| x.to_string()).collect()
    }

    fn bset(v: &[&str]) -> BTreeSet<String> {
        v.iter().map(|x| x.to_string()).collect()
    }

    #[test]
    fn schema_version_mismatch_rejected() {
        let p = std::env::temp_dir().join("bad-schema.json");
        std::fs::write(
            &p,
            r#"{"version":"v1","schema_version":"synonym-map-v0","synonyms":[]}"#,
        )
        .unwrap();
        let err = SynonymMap::load(&p).expect_err("should reject");
        assert!(format!("{err}").contains("schema_version mismatch"));
    }

    #[test]
    fn collision_detected() {
        let p = std::env::temp_dir().join("collision.json");
        std::fs::write(
            &p,
            r#"{
              "version":"v1",
              "schema_version":"synonym-map-v1",
              "synonyms":[
                {"canonical":"a","variants":["x"],"rationale":"","source":"t"},
                {"canonical":"b","variants":["x"],"rationale":"","source":"t"}
              ]
            }"#,
        )
        .unwrap();
        let err = SynonymMap::load(&p).expect_err("should reject");
        assert!(format!("{err}").contains("collision"));
    }

    #[test]
    fn canonicalize_normalizes_first() {
        let m = tiny_map();
        // Plural / case / whitespace all flow through normalize before lookup.
        assert_eq!(m.canonicalize("Standups"), "meeting");
        assert_eq!(m.canonicalize("vehicle_repair"), "car-repair");
        assert_eq!(m.canonicalize("KIDS"), "kid");
    }

    #[test]
    fn unknown_tag_passes_through_normalized() {
        let m = tiny_map();
        assert_eq!(m.canonicalize("brake-pads"), "brake-pad");
        assert_eq!(m.canonicalize("unrecognized"), "unrecognized");
    }

    #[test]
    fn canonicalize_set_collapses_duplicates_after_mapping() {
        let m = tiny_map();
        let out = m.canonicalize_set(&s(&["standup", "1on1", "kids"]));
        // standup and 1on1 both map to meeting; dedupe to one entry.
        assert_eq!(out, bset(&["meeting", "kid"]));
    }

    #[test]
    fn person_name_does_not_collapse_into_domain() {
        // Discipline rule: person-name tags stay distinct from
        // domain tags even when consistently paired.
        let m = tiny_map();
        let actual = m.canonicalize_set(&s(&["karen", "finance"]));
        let expected = m.canonicalize_set(&s(&["karen"]));
        assert_ne!(actual, expected);
    }

    #[test]
    fn specificity_collapse_only_when_synonyms() {
        let m = tiny_map();
        // auto-maintenance IS a synonym for car-repair: collapses.
        let car_synonym_set = m.canonicalize_set(&s(&["auto-maintenance"]));
        assert_eq!(car_synonym_set, bset(&["car-repair"]));
        // brake-pads is NOT a synonym for car-repair: stays distinct.
        let brake_set = m.canonicalize_set(&s(&["brake-pads"]));
        assert_ne!(brake_set, bset(&["car-repair"]));
        assert_eq!(brake_set, bset(&["brake-pad"]));
    }

    #[test]
    fn exact_match_after_canonicalization_counts_as_correct() {
        let m = tiny_map();
        let inputs = vec![TagCollapseInput {
            dictation_id: "d1".into(),
            entry_idx: 0,
            actual_tags: s(&["vehicle-repair"]),
            acceptable_tag_sets: vec![s(&["car-repair"])],
        }];
        let score = score_tag_collapse(&m, &inputs);
        assert_eq!(score.correct_at_exact, 1);
        assert_eq!(score.total_entries, 1);
        assert!((score.exact_percentage() - 100.0).abs() < 1e-9);
        assert!(score.per_entry[0].passed_at_exact);
        assert!((score.per_entry[0].best_jaccard - 1.0).abs() < 1e-9);
        assert!(score.near_miss_top.is_empty());
    }

    #[test]
    fn partial_overlap_does_not_pass_but_records_observational() {
        let m = tiny_map();
        let inputs = vec![TagCollapseInput {
            dictation_id: "d1".into(),
            entry_idx: 0,
            actual_tags: s(&["meeting", "kid"]),
            acceptable_tag_sets: vec![s(&["meeting"])],
        }];
        let score = score_tag_collapse(&m, &inputs);
        assert_eq!(score.correct_at_exact, 0);
        // 1/2 -> 0.5 jaccard
        assert!((score.per_entry[0].best_jaccard - 0.5).abs() < 1e-9);
        assert_eq!(score.correct_at_0_5, 1);
        assert_eq!(score.correct_at_0_67, 0);
        // Near-miss: extra `kid` on actual side.
        assert!(score
            .near_miss_top
            .iter()
            .any(|n| n.actual_tag == "kid" && n.expected_tag == "(extra)"));
    }

    #[test]
    fn max_jaccard_over_multiple_acceptable_sets() {
        let m = tiny_map();
        let inputs = vec![TagCollapseInput {
            dictation_id: "d1".into(),
            entry_idx: 0,
            actual_tags: s(&["car-repair"]),
            // First option doesn't match, second does.
            acceptable_tag_sets: vec![s(&["finance"]), s(&["car-repair"])],
        }];
        let score = score_tag_collapse(&m, &inputs);
        assert_eq!(score.correct_at_exact, 1);
    }

    #[test]
    fn near_miss_aggregates_across_entries() {
        let m = tiny_map();
        let inputs = vec![
            TagCollapseInput {
                dictation_id: "d1".into(),
                entry_idx: 0,
                actual_tags: s(&["brake-pads"]),
                acceptable_tag_sets: vec![s(&["car-repair"])],
            },
            TagCollapseInput {
                dictation_id: "d2".into(),
                entry_idx: 0,
                actual_tags: s(&["brake-pads"]),
                acceptable_tag_sets: vec![s(&["car-repair"])],
            },
        ];
        let score = score_tag_collapse(&m, &inputs);
        assert_eq!(score.correct_at_exact, 0);
        // Both miss the same way -> single near-miss row, frequency 2.
        let nm = score
            .near_miss_top
            .iter()
            .find(|n| n.actual_tag == "brake-pad" && n.expected_tag == "car-repair")
            .expect("near-miss should be present");
        assert_eq!(nm.frequency, 2);
        assert_eq!(nm.example_dictation_ids, vec!["d1", "d2"]);
    }

    #[test]
    fn person_distinct_keeps_score_low() {
        // The discipline rule has consequences: pairing karen + finance
        // (actual) vs. just finance (expected) is a miss, not equivalent.
        let m = tiny_map();
        let inputs = vec![TagCollapseInput {
            dictation_id: "d1".into(),
            entry_idx: 0,
            actual_tags: s(&["karen", "finance"]),
            acceptable_tag_sets: vec![s(&["finance"])],
        }];
        let score = score_tag_collapse(&m, &inputs);
        assert_eq!(score.correct_at_exact, 0);
        assert!((score.per_entry[0].best_jaccard - 0.5).abs() < 1e-9);
    }

    #[test]
    fn domain_overlap_not_equivalence() {
        // etsy / social-media â€” if both are auto-seeded as
        // canonicals with no cross-mapping, they MUST NOT collapse.
        // (No synonym entry between them in tiny_map.)
        let m = map_from_json(
            r#"{
              "version":"v1",
              "schema_version":"synonym-map-v1",
              "synonyms":[
                {"canonical":"etsy","variants":[],"rationale":"","source":"t"},
                {"canonical":"social-media","variants":[],"rationale":"","source":"t"}
              ]
            }"#,
        );
        let actual = m.canonicalize_set(&s(&["etsy"]));
        let expected = m.canonicalize_set(&s(&["social-media"]));
        assert_ne!(actual, expected);
    }

    #[test]
    fn empty_actual_and_empty_expected_passes() {
        let m = tiny_map();
        let inputs = vec![TagCollapseInput {
            dictation_id: "d1".into(),
            entry_idx: 0,
            actual_tags: Vec::new(),
            acceptable_tag_sets: vec![Vec::new()],
        }];
        let score = score_tag_collapse(&m, &inputs);
        assert_eq!(score.correct_at_exact, 1);
    }

    #[test]
    fn no_acceptable_sets_does_not_pass() {
        let m = tiny_map();
        let inputs = vec![TagCollapseInput {
            dictation_id: "d1".into(),
            entry_idx: 0,
            actual_tags: s(&["whatever"]),
            acceptable_tag_sets: Vec::new(),
        }];
        let score = score_tag_collapse(&m, &inputs);
        assert_eq!(score.correct_at_exact, 0);
        assert_eq!(score.total_entries, 1);
    }
}
