# One-shot fetcher for the Mockingbird design-language font bundle.
#
# Why a script and not "just commit some WOFF2s": the Google Fonts WOFF2
# service serves already-subset variable fonts per unicode-range, which
# is exactly what we want (smallest possible bundle, Latin only) and is
# what a browser would otherwise fetch every cold start. By running this
# script ONCE at W1 setup time, we materialise the files locally and the
# Google Fonts CDN is never consulted again. Re-run only when adding a
# new family or expanding the glyph range (e.g. adding Vietnamese).
#
# Output:
#   ui/public/fonts/*.woff2     — Latin + Latin-Ext WOFF2 files
#   ui/public/fonts/fonts.css   — local @font-face declarations
#
# All three families (Fraunces, DM Sans, IBM Plex Mono) are SIL OFL-
# licensed; redistribution + bundling are explicitly permitted.

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$root = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root 'ui\public\fonts'
New-Item -ItemType Directory -Path $outDir -Force | Out-Null

# Variable-axis specs matching the design language source HTML.
# Fraunces: opsz 9..144, wght 300..700 (display + headline)
# DM Sans:  opsz 9..40,  wght 300..700 (title + body)
# IBM Plex Mono: discrete 400 / 500 / 600 (labels + numbers + code)
$cssUrl = 'https://fonts.googleapis.com/css2?' +
          'family=Fraunces:opsz,wght@9..144,300..700&' +
          'family=DM+Sans:opsz,wght@9..40,300..700&' +
          'family=IBM+Plex+Mono:wght@400;500;600&' +
          'display=swap'

# Browser-y UA so the API returns WOFF2 (not TTF or older formats).
$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/120.0'

Write-Host "[1/3] Fetch Google Fonts CSS manifest" -ForegroundColor Cyan
$css = (Invoke-WebRequest -Uri $cssUrl -UserAgent $ua -UseBasicParsing).Content

# Parse into @font-face blocks. Each block has:
#   - font-family (quoted)
#   - font-weight range
#   - the WOFF2 src URL
#   - a comment line above it naming the unicode-range subset
# We want only `latin` and `latin-ext`; skip cyrillic / vietnamese / greek.
$blocks = [regex]::Matches(
    $css,
    '/\* (?<subset>[\w-]+) \*/\s*@font-face \{(?<body>[^}]+)\}',
    'Singleline'
)

Write-Host ("[2/3] Found " + $blocks.Count + " @font-face blocks; filtering to latin + latin-ext")  -ForegroundColor Cyan

$localBlocks = @()
$downloaded = 0
foreach ($b in $blocks) {
    $subset = $b.Groups['subset'].Value
    if ($subset -notin @('latin', 'latin-ext')) { continue }

    $body = $b.Groups['body'].Value
    $family = ([regex]::Match($body, "font-family:\s*'([^']+)'")).Groups[1].Value
    $weight = ([regex]::Match($body, 'font-weight:\s*([^;]+);')).Groups[1].Value.Trim()
    $srcUrl = ([regex]::Match($body, 'url\((https://[^)]+\.woff2)\)')).Groups[1].Value
    if (-not $srcUrl) { continue }

    # Stable local filename: family + subset (no version hashing — we
    # want a clean filename that doesn't change if Google re-serves a
    # different revision later).
    $safeFamily = $family.Replace(' ', '')
    $localName  = ('{0}-{1}.woff2' -f $safeFamily, $subset)
    $localPath  = Join-Path $outDir $localName

    if (-not (Test-Path $localPath)) {
        Write-Host ("    download {0,-26} ({1})" -f $localName, $subset)
        Invoke-WebRequest -Uri $srcUrl -OutFile $localPath -UseBasicParsing
        $downloaded++
    } else {
        Write-Host ("    skip     {0,-26} (already on disk)" -f $localName)
    }

    # Rewrite block body to point at the local file instead of gstatic.
    $localBody = $body -replace [regex]::Escape($srcUrl), ('./' + $localName)
    $localBlocks += "/* $subset */`n@font-face {$localBody}`n"
}

Write-Host ("[3/3] Wrote " + $downloaded + " new file(s); building fonts.css")  -ForegroundColor Cyan

$header = @"
/* Mockingbird design-language v1 — local @font-face declarations.
 *
 * Generated by scripts/dev/download-design-fonts.ps1 from the Google Fonts
 * WOFF2 service (Latin + Latin-Ext subsets only). Re-run that script
 * to regenerate. NEVER hand-edit this file — your edits will be
 * clobbered on the next regeneration.
 *
 * All three families are SIL OFL-licensed; bundling permitted.
 * Loaded once at app start; afterwards the OS font cache serves
 * subsequent windows. No network traffic at runtime.
 */

"@

($header + ($localBlocks -join "`n")) | Out-File -Encoding utf8 -NoNewline (Join-Path $outDir 'fonts.css')

$totalBytes = (Get-ChildItem $outDir -Filter '*.woff2' | Measure-Object Length -Sum).Sum
Write-Host ("`nDone. Bundle size: " + [Math]::Round($totalBytes / 1KB, 1) + " KB across " + (Get-ChildItem $outDir -Filter '*.woff2').Count + " WOFF2 files.") -ForegroundColor Green
