#!/usr/bin/env bash
# Seed the macOS-port bead tree per the locked master plan
# (repo-kennel drawer 48).
#
# Convention: the epic gets the explicit slug ID "mb-mac-v1"
# (bd allows --id when no --parent is set). All children are
# created with --parent (bd then refuses --id) so they get
# auto-assigned hash IDs; we capture the slug→ID mapping to
# docs/macos-port/bead-map.md as the source of truth.

set -u
OWNER="planning-agent-d2b683"
MAP="docs/macos-port/bead-map.md"

mkdir -p "$(dirname "$MAP")"
cat >"$MAP" <<'EOF'
# macOS-port bead tree — slug→ID map

Generated by `scripts/dev/seed-bead-tree-mac.sh` during Phase 0 Leaf 0.2.
The "slug" column is the human-readable name from the master plan
(repo-kennel drawer 48); the "id" column is the bd-assigned ID used by
`bd show / bd ready / bd close`. Use the slug in commit messages and
docs; use the id when calling bd.

| slug | id | type | parent |
|------|----|------|--------|
EOF

# create_root: --id allowed (no parent). Used only for the epic.
create_root() {
  local id="$1" title="$2" judge="$3" desc="$4" extra="${5:-}"
  local args=(create "$title" --silent --id "$id" --assignee "$OWNER"
              --acceptance "Judge: $judge" --description "$desc")
  # shellcheck disable=SC2206
  [ -n "$extra" ] && args+=($extra)
  local out
  out=$(bd "${args[@]}" 2>&1 | tail -1)
  echo "$id  ->  $out  ($title)" >&2
  printf "| %s | %s | epic | — |\n" "$id" "$id" >>"$MAP"
}

# create_child: --parent, auto-ID. Captures slug→ID into the map.
create_child() {
  local slug="$1" title="$2" parent_slug="$3" parent_id="$4"
  local judge="$5" desc="$6" itype="${7:-task}"
  local args=(create "$title" --silent --type "$itype" --assignee "$OWNER"
              --parent "$parent_id"
              --acceptance "Judge: $judge"
              --description "[$slug] $desc")
  local out
  out=$(bd "${args[@]}" 2>&1 | tail -1)
  if [[ ! "$out" =~ ^mb- ]]; then
    echo "ERROR creating $slug: $out" >&2
    return 1
  fi
  echo "$slug  ->  $out" >&2
  printf "| %s | %s | %s | %s |\n" "$slug" "$out" "$itype" "$parent_slug" >>"$MAP"
  # Echo the auto-ID so caller can capture it for nested parents.
  echo "$out"
}

# ---------- Epic ----------
create_root "mb-mac-v1" \
  "macOS v1 — Windows-parity dictation + meeting capture (Apple Silicon)" \
  "mac-v1-dictation-e2e + mac-v1-meeting-capture-e2e" \
  "Anchor epic for the macOS port. Scope: dictation (P3) + meeting capture (P4). KG/activity DEFERRED." \
  "--type epic"

EPIC="mb-mac-v1"

# ---------- Phase 0 ----------
P0=$(create_child "mb-mac-p0-bootstrap" \
  "Phase 0 — tracking-machinery bootstrap on Mac" \
  "mb-mac-v1" "$EPIC" "all p0 leaves closed" \
  "Stand up bd / judges / wiggum / docs-audit / goal on this Mac before touching code.")
create_child "mb-mac-p0-verify-toolchain" "Verify macOS toolchain present" \
  "mb-mac-p0-bootstrap" "$P0" "mac-p0-toolchain-present" \
  "git, rustc>=1.77, node>=20, cargo tauri, bd, xcode-select -p all resolve. uname Darwin/arm64. branch=macos-port." >/dev/null
create_child "mb-mac-p0-bd-init" "Initialize .beads/ and create full bead tree" \
  "mb-mac-p0-bootstrap" "$P0" "bd ready lists p1 leaves; bd show mb-mac-v1 shows tree" \
  "bd init --prefix mb; create every bead in this tree; assign owner planning-agent-d2b683." >/dev/null
create_child "mb-mac-p0-judges-seed-mac" "Author seed-judges.sh and install 21 mac judges" \
  "mb-mac-p0-bootstrap" "$P0" "~/.code_puppy/judges.json contains all mac-* IDs" \
  "Mac equivalent of seed-judges.ps1 (jq merger). Inputs: .code_puppy/judges-template.json + judges-template-macos.json. Output: ~/.code_puppy/judges.json." >/dev/null
create_child "mb-mac-p0-wiggum-rules-mac" "Author 4 new wiggum hooks + lefthook wiring" \
  "mb-mac-p0-bootstrap" "$P0" "Synthetic-input tests pass for each hook" \
  "block-push-to-main.py, block-windows-rs-edit-on-macport.py, block-stt-swap.py, verify-cargo-build-jobs.py." >/dev/null
create_child "mb-mac-p0-carry-docs-audit" "Audit presence of all required carry docs" \
  "mb-mac-p0-bootstrap" "$P0" "Every required doc PRESENT or surfaced as MISSING" \
  ".code_puppy/, PLAN-mockingbird-v2.md, STATUS.md, AGENTS.md, docs/adr/, docs/phases/, docs/judges/, experimental/kg-validation/." >/dev/null
create_child "mb-mac-p0-goal-install" "Install the mac-v1 persistent goal" \
  "mb-mac-p0-bootstrap" "$P0" "goal mac-v1 visible to next agent session" \
  "Install the mac-v1 anti-drift goal text into Code Puppy goal store + pin to STATUS.md top." >/dev/null

# ---------- Phase 1 ----------
P1=$(create_child "mb-mac-p1-baseline-build" "Phase 1 — baseline build green on macOS" \
  "mb-mac-v1" "$EPIC" "all p1 leaves closed" \
  "UI + cargo check + tauri dev window opens on Mac.")
create_child "mb-mac-p1-secrets-mod-audit" "Audit secrets/mod.rs non-Windows routing" \
  "mb-mac-p1-baseline-build" "$P1" "mac-cargo-gate (cargo check on secrets::)" \
  "Confirm secrets/mod.rs falls through to stub.rs under #[cfg(not(target_os=windows))]." >/dev/null
create_child "mb-mac-p1-ui-ci-build" "UI: npm ci --ignore-scripts && npm run build" \
  "mb-mac-p1-baseline-build" "$P1" "mac-ui-gate" \
  "tsc --noEmit + vite build green; dist/ populated." >/dev/null
create_child "mb-mac-p1-cargo-check" "Workspace cargo check (CPU-only, CARGO_BUILD_JOBS=2)" \
  "mb-mac-p1-baseline-build" "$P1" "mac-cargo-gate (check subset)" \
  "No --features cuda. Errors fail; unused-stub warnings OK." >/dev/null
create_child "mb-mac-p1-tauri-dev-launch" "cargo tauri dev opens Mockingbird window" \
  "mb-mac-p1-baseline-build" "$P1" "mac-p1-window-opens" \
  "Manual smoke. Hotkey/audio/paste/STT non-functional expected (stubs)." >/dev/null

# ---------- Phase 2 ----------
P2=$(create_child "mb-mac-p2-toolchain-swap" "Phase 2 — Metal STT toolchain" \
  "mb-mac-v1" "$EPIC" "all p2 leaves closed" \
  "whisper-rs/metal feature gated; ORT dylib discovered; clip transcribes via Metal.")
create_child "mb-mac-p2-whisper-metal-feature" "Cargo metal feature gate for whisper-rs" \
  "mb-mac-p2-toolchain-swap" "$P2" "mac-cargo-gate (--features metal)" \
  "src-tauri/Cargo.toml: metal = [\"whisper-rs/metal\"]; defaults unchanged." >/dev/null
create_child "mb-mac-p2-ort-dylib-discovery" "ORT libonnxruntime.dylib path discovery (cargo-mac.sh)" \
  "mb-mac-p2-toolchain-swap" "$P2" "ort loads at runtime; no panic on missing dylib" \
  "Mac equivalent of cargo-with-cuda.ps1. New scripts/dev/cargo-mac.sh." >/dev/null
create_child "mb-mac-p2-whisper-clip-transcribe" "Eval clip → non-empty transcript via Metal" \
  "mb-mac-p2-toolchain-swap" "$P2" "mac-p2-metal-transcript" \
  "cargo run --example mac_whisper_metal_smoke <fixture.wav>." >/dev/null

# ---------- Phase 3 ----------
P3=$(create_child "mb-mac-p3-dictation" "Phase 3 — DICTATION on macOS (priority 1)" \
  "mb-mac-v1" "$EPIC" "mac-p3-dictation-e2e + composite" \
  "Hotkey -> speak -> cleaned transcript pastes into foreground app.")
create_child "mb-mac-p3a-secrets-keychain" "Keychain-backed SecretStore (security-framework)" \
  "mb-mac-p3-dictation" "$P3" "mac-p3a-keychain-roundtrip" \
  "CREATE src-tauri/src/secrets/macos.rs. Route via #[cfg(target_os=macos)]. ADR required." >/dev/null
create_child "mb-mac-p3b-injection-paste" "CGEvent cmd+v paste + clipboard save/restore" \
  "mb-mac-p3-dictation" "$P3" "mac-p3b-paste-clipboard-saverestore" \
  "Fill injection/macos.rs. Reuse arboard for clipboard save/restore." >/dev/null
create_child "mb-mac-p3c-secure-input-ax" "Accessibility AX secure-input detection" \
  "mb-mac-p3-dictation" "$P3" "mac-p3c-secure-input-aborts" \
  "kAXSecureTextFieldRole probe; abort + toast on hit." >/dev/null
create_child "mb-mac-p3d-hotkey-eventtap" "CGEventTap hotkey driver" \
  "mb-mac-p3-dictation" "$P3" "mac-p3d-hotkey-roundtrip" \
  "Reuse hotkey::state state machine. Requires Input Monitoring permission." >/dev/null
create_child "mb-mac-p3e-window-context-nsworkspace" "NSWorkspace frontmost-app reader" \
  "mb-mac-p3-dictation" "$P3" "mac-p3e-frontmost-app-readable" \
  "Fill window_context/macos.rs. Minimal: bundleID + app name." >/dev/null
create_child "mb-mac-p3f-permissions-onboarding" "First-launch permissions panel" \
  "mb-mac-p3-dictation" "$P3" "mac-p3f-permissions-onboarding-renders" \
  "Mic, Input Monitoring, Accessibility (and Screen Recording in P4). Deep-link to prefs panes." >/dev/null

# ---------- Phase 4 ----------
P4=$(create_child "mb-mac-p4-meeting-capture" "Phase 4 — MEETING CAPTURE on macOS (priority 2)" \
  "mb-mac-v1" "$EPIC" "mac-p4-meeting-capture-e2e + composite" \
  "Local + remote attribution via ScreenCaptureKit + cpal.")
create_child "mb-mac-p4a-mic-only-meeting" "Mic-only meeting roundtrip (cpal)" \
  "mb-mac-p4-meeting-capture" "$P4" "mac-p4a-mic-meeting-roundtrip" \
  "Prove meeting data model + UI + storage before SCK. De-risks downstream." >/dev/null
create_child "mb-mac-p4b-screencapturekit-ffi" "ADR: SCK Swift/ObjC bridge design" \
  "mb-mac-p4-meeting-capture" "$P4" "ADR review passes; no code yet" \
  "docs/adr/00XX-mac-screencapturekit-bridge.md. Build-system, FFI surface, lifetime." \
  "decision" >/dev/null
create_child "mb-mac-p4b-screencapturekit-bridge" "Implement SCK bridge (16kHz mono)" \
  "mb-mac-p4-meeting-capture" "$P4" "mac-p4b-permission-silence-detector" \
  "SCStreamConfiguration capturesAudio+captureMicrophone, dummy off-screen filter." >/dev/null
create_child "mb-mac-p4b-source-tagging" "SCStreamSampleBufferAttachment.microphoneStream classifier" \
  "mb-mac-p4-meeting-capture" "$P4" "mac-p4b-sck-source-tagging" \
  "Per-buffer mic vs system audio classification." >/dev/null
create_child "mb-mac-p4c-dual-stream-merge" "Transcribe two streams independently and merge with attribution" \
  "mb-mac-p4-meeting-capture" "$P4" "mac-p4c-dual-stream-attribution" \
  "BlackHole virtual-device fallback path documented." >/dev/null

# ---------- Phase 5 ----------
P5=$(create_child "mb-mac-p5-validation" "Phase 5 — Full local validation" \
  "mb-mac-v1" "$EPIC" "all p5 leaves closed" \
  "Ollama installed, parity eval green, 8GB canary characterized.")
create_child "mb-mac-p5-ollama-install" "Install Ollama + pull cleanup model" \
  "mb-mac-p5-validation" "$P5" "ollama list shows model; localhost:11434 responds 200" \
  "Recommended cleanup model TBD by p5-8gb-canary." >/dev/null
create_child "mb-mac-p5-parity-eval" "Run eval corpus vs Windows-CUDA goldens" \
  "mb-mac-p5-validation" "$P5" "mac-v1-parity-whisper-metal" \
  "WER/CER within budget on the shared eval corpus." >/dev/null
create_child "mb-mac-p5-8gb-canary" "Characterize 8 GB Mac canary; pick default model" \
  "mb-mac-p5-validation" "$P5" "documented in docs/runbooks/macos-8gb-canary.md" \
  "No thrash under canonical workload." >/dev/null

echo
echo "=== Bead count ==="
bd count
